version: '3'
services:
  web:
    build: .
    command: hugo server -p 5000 --bind 0.0.0.0 -b http://orbital.japura.net:5000
    volumes:
      - .:/go/src/app/
    ports:
      - "5000:5000"
    environment:
      - HUGO_ENV
